name: Docker and Maven Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

  test: 
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

  build:
    needs: test
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Prepare script permissions
      run: |
        chmod 777 run.sh
    - name: Build container
      run: |
        if [[ -z $(docker ps -a -q -f name=soap) ]]; then
          docker build -t soap -f dockerSOAP.Dockerfile .
        else
          docker stop soap && docker rm soap && docker rmi soap
          docker build -t soap -f dockerSOAP.Dockerfile .
        fi
    - name: Run
      run: ./run.sh
    
