name: Docker and Maven Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Prepare script permissions
      run: |
        chmod 777 run.sh
    - name: stop docker
      run: |
        docker compose down --rmi all --remove-orphans
    - name: Run
      run: ./run.sh
    
